import type { Metadata } from "next";
import "./globals.css";
import { languages } from "@/i18n/settings";
import { ChildProps } from "@/types";
import { Toaster } from "@/components/ui/sonner";
import { Sora, Poppins, Inter, Manrope } from "next/font/google";
import { CookieProvider } from "@/components/providers/cooke-provider";
import NextTopLoader from "nextjs-toploader";

const sora = Sora({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-sora",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-manrope",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Texnotech uz",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

interface Props extends ChildProps {
  params: {
    lng: string;
  };
}

function RootLayout({ children, params: { lng } }: Props) {
  return (
    <html lang={lng} suppressHydrationWarning>
      <body
        className={`${sora.variable} ${manrope.variable} ${poppins.variable} ${inter.variable} overflow-x-hidden antialiased`}
      >
        <NextTopLoader showSpinner={false} />
        <CookieProvider>{children}</CookieProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
export default RootLayout;

// 1- Ui uchun shadcn ui + Tailwindcss

// 2- Tillar uchun i18n til middlewaresi uchun next-intel i18n fayili ichida konfiglar va locales da jsonlar va middlewareda doyim qo'shimcha turishi uchun yani /uz /ru

// 3- Rasim yuklash uchun Uploadthing api/uploadthing ni ichida configlar lib/uploadthing.ts ni ichida configlarni Buttonlarga beryapmiz va lib/uploadthing.ts ni ichidan import qilib ishlatyapmiz

// 4- State menejment Redux toolkit orqali | npm install @reduxjs/toolkit react-redux

// git add .
// git commit -m "Updated"
// git push

// git add .
// GIT_AUTHOR_DATE="2026-01-25T12:00:00" \
// GIT_COMMITTER_DATE="2026-01-25T12:00:00" \
// git commit -m "Admin updated"
// git push
